In [14]:
import numpy as np
a=np.array([1,2,3])
print("\ntype:%s"%type(a))
print("\nshape:%s"%a.shape)
print(a[0],a[1],a[2])
a[0]=5
print(a)
b=np.array([[1,2,3],[4,5,6]])
print("\nshape of b:",b.shape)
print(b[0,0],b[0,1],b[1,0])
a=np.zeros((1,2))
print("\nAll zeros matrix:\n%s"%a)
b=np.zeros((1,2))
print("\n All ones matrix:\n%s"%b)
d=np.eye(2)
print("\n Identity matrix:\n%s"%d)
e=np.random.random((2,2))
print("\n Random matrix:\n%s"%e)
print("\nVectorized sum example\n")
x=np.array([[1,2],[3,4]])
print("x:\n%s"%x)
print("\nsum:%s"%np.sum(x))
print("\nsum axis=0:%s"%np.sum(x,axis=0))
print("\nsum axis=1:%s"%np.sum(x,axis=1))
a=np.arange(10000)
b=np.arange(10000)
dp=np.dot(a,b)
print("\nDot product:%s\n"%dp)
op=np.outer(a,b)
print("\n Outer product:%s\n"%op)
ep=np.multiply(a,b)
print("\n Element wise product:%s\n"%ep)


type:<class 'numpy.ndarray'>

shape:3
1 2 3
[5 2 3]

shape of b: (2, 3)
1 2 4

All zeros matrix:
[[0. 0.]]

 All ones matrix:
[[0. 0.]]

 Identity matrix:
[[1. 0.]
 [0. 1.]]

 Random matrix:
[[0.10728933 0.7055971 ]
 [0.86897018 0.61188581]]

Vectorized sum example

x:
[[1 2]
 [3 4]]

sum:10

sum axis=0:[4 6]

sum axis=1:[3 7]

Dot product:-1724114088


 Outer product:[[       0        0        0 ...        0        0        0]
 [       0        1        2 ...     9997     9998     9999]
 [       0        2        4 ...    19994    19996    19998]
 ...
 [       0     9997    19994 ... 99940009 99950006 99960003]
 [       0     9998    19996 ... 99950006 99960004 99970002]
 [       0     9999    19998 ... 99960003 99970002 99980001]]


 Element wise product:[       0        1        4 ... 99940009 99960004 99980001]



In [9]:
import numpy as np
x=np.array([[1,2],[3,4]])
print("ORIGINAL X:\n%s"%x)
print("\n Transpose of x:\n%s"%x.T)

ORIGINAL X:
[[1 2]
 [3 4]]

 Transpose of x:
[[1 3]
 [2 4]]


In [12]:
from numpy import array
from scipy.linalg import svd
a=array([[1,2],[3,4],[5,6]])
print("a:\n%s"%a)
u,s,vt=svd(a)
print("\nu:\n%s"%u)
print("\ns:\n%s"%s)
print("\nvt:\n%s"%vt)

a:
[[1 2]
 [3 4]
 [5 6]]

u:
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

s:
[9.52551809 0.51430058]

vt:
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
